"""This file is auto-generated by enumsync. Do not edit this file directly."""

from enum import StrEnum
from typing import TypeAlias

from enumsync import FileStore


class Example1Enum(StrEnum):
    ExpectedPy = "expected.py"
    ReadmeMd = "README.md"


FileStore(__file__).sync()
Example1FileStore: TypeAlias = FileStore[Example1Enum]
__all__ = ["Example1Enum", "Example1FileStore"]
