import ast
import re
from ast import (
    AnnAssign,
    Assign,
    ClassDef,
    Constant,
    Expr,
    ImportFrom,
    List,
    Load,
    Module,
    Name,
    Store,
    Subscript,
    alias,
)
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import TYPE_CHECKING, Iterable

if TYPE_CHECKING:
    from enumsync.store import FileStore
else:
    FileStore = object
try:
    import ruff
except ImportError:
    ruff = None


def to_pascal(name: str) -> str:
    parts = re.split(r"[^0-9A-Za-z]+", name)
    return "".join(part.capitalize() for part in parts if part)


IMPORT_BLOCKS = [
    ImportFrom(module="enum", names=[alias(name="StrEnum")], level=0),
    ImportFrom(module="typing", names=[alias(name="TypeAlias")], level=0),
    ImportFrom(module="enumsync", names=[alias(name="FileStore")], level=0),
]


class ModuleBuilder:
    def define_import_blocks(self) -> list[ImportFrom]:
        return IMPORT_BLOCKS

    def define_enum_sync_block(
        self, store: FileStore, glob: Iterable[Path]
    ) -> ClassDef:
        prefix = to_pascal(store.folder.name) or "Synced"
        enum_body = {
            to_pascal(path.name): path.relative_to(store.folder).as_posix()
            for path in glob
            if path.is_file() and path.name != "__init__.py"
        }
        return ClassDef(
            name=f"{prefix}Enum",
            bases=[Name(id="StrEnum", ctx=Load())],
            keywords=[],
            body=[
                *[
                    Assign(
                        targets=[Name(id=name, ctx=Store())],
                        value=Constant(value=value),
                    )
                    for name, value in enum_body.items()
                ]
            ],
            decorator_list=[],
            type_params=[],
        )

    def define_comment_block(self) -> Expr:
        return ast.parse(
            '"""This file is auto-generated by enumsync. Do not edit this file directly."""'
        ).body[
            0
        ]  # type: ignore

    def define_sync_block(self) -> Expr:
        return ast.parse("FileStore(__file__).sync()").body[0]  # type: ignore

    def define_domain_file_sotre(self, store: FileStore) -> AnnAssign:
        prefix = to_pascal(store.folder.name)

        return AnnAssign(
            target=Name(id=f"{prefix}FileStore", ctx=Store()),
            annotation=Name(id="TypeAlias", ctx=Load()),
            value=Subscript(
                value=Name(id="FileStore", ctx=Load()),
                slice=Name(id=f"{prefix}Enum", ctx=Load()),
                ctx=Load(),
            ),
            simple=1,
        )

    def define_export_all_block(self, store: FileStore) -> Assign:
        prefix = to_pascal(store.folder.name)
        return Assign(
            targets=[Name(id="__all__", ctx=Store())],
            value=List(
                elts=[
                    Constant(value=f"{prefix}Enum"),
                    Constant(value=f"{prefix}FileStore"),
                ],
                ctx=Load(),
            ),
        )

    def define(self, store: FileStore) -> Module:
        module = Module(
            body=[
                self.define_comment_block(),
                *self.define_import_blocks(),
                self.define_enum_sync_block(store, store.glob("*.*")),
                self.define_sync_block(),
                self.define_domain_file_sotre(store),
                self.define_export_all_block(store),
            ],
            type_ignores=[],
        )
        return ast.fix_missing_locations(module)


def generate_sync_code(store: FileStore) -> str:
    builder = ModuleBuilder()
    module = builder.define(store)
    code = ast.unparse(module)
    try:
        format_code(code)
    except Exception:
        pass
    return code


def format_code(code: str) -> str:
    if ruff is None:
        return code
    from ruff import find_ruff_bin

    with TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir) / "temp.py"
        temp_path.write_text(code, encoding="utf-8")
        ruff_bin = find_ruff_bin()
        subprocess.check_call([ruff_bin, "format", temp_path])
        code = temp_path.read_text(encoding="utf-8")
    return code
